function [] = makeGUI
global h_fig 
global Button_addarea Button_addpassfilter Button_addnopassfilter Button_importfilter 
global Button_exit Button_showIm Button_showImF
global Button_save Button_lighter Text_outfilename
global Type_circle Type_square Type_addpass Type_addnotpass 
global Text_theta Text_matname
global appearance % 1 for circle, 2 for square
global pass % 1 for pass, 0 for not pass
global theta
global needshowIm needshowImF scrsz needlighter
global Imsize ImF ImFFilt ImOut Im Filt
global filename
appearance = 1;
pass = 0;
theta = 0;
%% 设置UI控件
% 创建一个图形界面，起名字
scrsz = get(0,'screensize');
scrsz(1,1:2)=0.1*scrsz(1,3:4);
scrsz(3)=0.8*scrsz(3);
scrsz(4)=0.9*scrsz(4);
h_fig=figure('toolbar','none',...
    'position',0.9*scrsz,...
    'name','光学空间频率域滤波演示'); 
% 创建一个按钮，从全通新建滤波器
Button_addpassfilter=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','w',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','从全通新建滤波器',...
    'position',[50,scrsz(4)*4/5,200,40],...
    'callback','addPassFilter;');
% 创建一个按钮，从全阻新建滤波器
Button_addnopassfilter=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','w',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','从全阻新建滤波器',...
    'position',[50,scrsz(4)*4/5-50,200,40],...
    'callback','addNoPassFilter;');
% 创建一个按钮，从矩阵导入滤波器
Button_importfilter=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','w',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','从矩阵导入滤波器，矩阵名：',...
    'position',[50,scrsz(4)*4/5-100,200,40],...
    'callback','importFilter;');
% 创建一个text，导入矩阵的名字
Text_matname=uicontrol('parent',h_fig,...
    'style','edit',...
    'fontsize',10,...
    'Enable','On',...
    'fontweight','demi',...
    'position',[255,scrsz(4)*4/5-100,60,40]);

% 创建一个按钮，添加区域
Button_addarea=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','w',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','添加区域',...
    'Enable','Off',...
    'position',[50,scrsz(4)*4/5-300,150,40],...
    'callback','addArea;');

% 创建一个radiobutton，选则圆形
Type_circle=uicontrol('parent',h_fig,...
    'style','radiobutton',...
    'fontsize',10,...
    'value',1,...
    'fontweight','demi',...
    'string','圆形',...
    'Enable','Off',...
    'position',[50,scrsz(4)*4/5-150,150,30],...
    'callback','set(Type_circle,''value'',1);set(Type_square,''value'',0);set(Text_theta,''Enable'',''Off'');appearance=1;');
% 创建一个radiobutton，选则方形
Type_square=uicontrol('parent',h_fig,...
    'style','radiobutton',...
    'fontsize',10,...
    'value',0,...
    'fontweight','demi',...
    'string','方形：顺时针旋转角度（°）',...
    'Enable','Off',...
    'position',[50,scrsz(4)*4/5-180,200,30],...
    'callback','set(Type_circle,''value'',0);set(Type_square,''value'',1);set(Text_theta,''Enable'',''On'');appearance=2;'); 

% 创建一个radiobutton，选则添加能通过的区域
Type_addpass=uicontrol('parent',h_fig,...
    'style','radiobutton',...
    'fontsize',10,...
    'value',0,...
    'fontweight','demi',...
    'string','添加能通过的区域',...
    'Enable','Off',...
    'position',[50,scrsz(4)*4/5-220,150,30],...
    'callback','set(Type_addpass,''value'',1);set(Type_addnotpass,''value'',0);pass=1;'); 
% 创建一个radiobutton，选则添加要阻挡的区域
Type_addnotpass=uicontrol('parent',h_fig,...
    'style','radiobutton',...
    'fontsize',10,...
    'value',1,...
    'fontweight','demi',...
    'string','添加想阻挡的区域',...
    'Enable','Off',...
    'position',[50,scrsz(4)*4/5-250,150,30],...
    'callback','set(Type_addpass,''value'',0);set(Type_addnotpass,''value'',1);pass=0;'); 

% 创建一个text，长方形顺时针旋转的角度
Text_theta=uicontrol('parent',h_fig,...
    'style','edit',...
    'fontsize',10,...
    'Enable','Off',...
    'fontweight','demi',...
    'string','0',...
    'position',[250,scrsz(4)*4/5-180,50,30]);

% 创建一个按钮，退出
Button_exit=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','y',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','退出',...
    'position',[50,20,200,40],...
    'callback','close all;');
% 创建一个按钮，显示/关闭原图像
Button_showIm=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','w',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','显示原图片',...
    'position',[50,70,95,40],...
    'callback','showIm;');
% 创建一个按钮，显示/关闭原频谱
Button_showImF=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','w',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','显示原频谱',...
    'position',[155,70,95,40],...
    'callback','showImF;');

% 创建一个按钮，保存图像
Button_save=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','w',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','保存图像到：文件名：',...
    'position',[50,scrsz(4)*4/5-345,150,40],...
    'callback','saveIm');

% 创建一个text，保存的文件名
Text_outfilename=uicontrol('parent',h_fig,...
    'style','edit',...
    'fontsize',10,...
    'Enable','On',...
    'fontweight','demi',...
    'string',filename(11:length(filename)-4),...
    'position',[210,scrsz(4)*4/5-345,100,40]);

% 创建一个按钮，增加图像亮度
Button_lighter=uicontrol('parent',h_fig,...
    'style','pushbutton',...
    'backgroundcolor','w',...
    'fontsize',10,...
    'fontweight','demi',...
    'string','增加图像亮度',...
    'position',[50,scrsz(4)*4/5-390,150,40],...
    'callback','lighter;');

needshowIm=1;needshowImF=1;needlighter=1;